### ISSUE TITLE
bug: timesfm loading from local path error

### ISSUE THREAD

**Issue by JitaekJo** [TimeCopilot/timecopilot#241]
### Initial Checklist

- [x] I confirm that I'm using the latest version of TimeCopilot.
- [x] I confirm that I've reviewed my issue at https://github.com/AzulGarza/timecopilot/issues before opening this one.

### What happened?

Hi,
after updating to 0.2.0, when I run Timesfm 2.5 200m pytorch locally, 
I face the error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], [line 102](vscode-notebook-cell:?execution_count=5&line=102)
     88 tcf = TimeCopilotForecaster(models=[
     89     chronos, #아마존
     90     moirai, #세일즈포스
   (...)
     97    
     98     ]) #<- 여기 다변화 줘야 함
    100 df = pd.read_excel("(분석용) Z Fold 6_raw - w1_250126.xlsx")
--> [102](vscode-notebook-cell:?execution_count=5&line=102) res = tcf.forecast(
    103     df=df,
    104     h=2,
    105     freq="W"
    106 )
    108 def explain_with_llm(table_md: str, prompt=
    109                      """
    110                      Please forecast.
   (...)
    114                      
    115                      """):
    116     base = os.environ.get("OPENAI_BASE_URL", "http://106.109.10.130:11434/v1").rstrip("/")

File c:\Users\jitaek.jo\AppData\Local\Programs\Python\Python312\Lib\site-packages\timecopilot\forecaster.py:177, in TimeCopilotForecaster.forecast(self, df, h, freq, level, quantiles)
    122 def forecast(
...
--> [167](file:///C:/Users/jitaek.jo/AppData/Local/Programs/Python/Python312/Lib/site-packages/timecopilot/models/foundation/timesfm.py:167) tfm.compile(config)
    168 try:
    169     yield tfm

**AttributeError: 'NoneType' object has no attribute 'compile'**

### Environment

```Text
0.0.20. win 11
```

**Comment by JitaekJo** [comment]
It seems like there is a problem with recognizing the local cash path for Timesfm
